### ISSUE TITLE
Support fastboot

### ISSUE THREAD

**Issue by mabab** [cardstack/glimmer-scoped-css#25]
Is there any way to support fastboot?
After install the ember-cli-fastboot package to test-app, I get an error every time I render a page.

Error occurred:

- While rendering:
  -top-level
    application

There was an error running your app in fastboot. More info about the error:
 ReferenceError: Cannot access '__WEBPACK_DEFAULT_EXPORT__' before initialization
    at Module.default (webpack://test-app/./components/outer.js?:3:42)
    at Resolver._extractDefaultExport (webpack://test-app/../rewritten-packages/ember-resolver.7aaf7ce6/node_modules/ember-resolver/resolvers/classic/index.js?:390:25)
    at Resolver.resolveOther (webpack://test-app/../rewritten-packages/ember-resolver.7aaf7ce6/node_modules/ember-resolver/resolvers/classic/index.js?:150:32)
    at Resolver.resolve (webpack://test-app/../rewritten-packages/ember-resolver.7aaf7ce6/node_modules/ember-resolver/resolvers/classic/index.js?:171:23)
    at resolve (/var/folders/gl/c42_2hp924lfn758_fsfbzl80000gn/T/broccoli-329491Acw9O3IGCE1/out-546-packager_runner_embroider_webpack/assets/@ember/-internals/container/index.js:764:1)
    at Registry.resolve (/var/folders/gl/c42_2hp924lfn758_fsfbzl80000gn/T/broccoli-329491Acw9O3IGCE1/out-546-packager_runner_embroider_webpack/assets/@ember/-internals/container/index.js:522:1)
    at Registry.resolve (/var/folders/gl/c42_2hp924lfn758_fsfbzl80000gn/T/broccoli-329491Acw9O3IGCE1/out-546-packager_runner_embroider_webpack/assets/@ember/-internals/container/index.js:524:1)
    at factoryFor (/var/folders/gl/c42_2hp924lfn758_fsfbzl80000gn/T/broccoli-329491Acw9O3IGCE1/out-546-packager_runner_embroider_webpack/assets/@ember/-internals/container/index.js:237:1)
    at Container.factoryFor (/var/folders/gl/c42_2hp924lfn758_fsfbzl80000gn/T/broccoli-329491Acw9O3IGCE1/out-546-packager_runner_embroider_webpack/assets/@ember/-internals/container/index.js:184:1)
    at ApplicationInstance.factoryFor (/var/folders/gl/c42_2hp924lfn758_fsfbzl80000gn/T/broccoli-329491Acw9O3IGCE1/out-546-packager_runner_embroider_webpack/assets/@ember/-internals/runtime/lib/mixins/container_proxy.js:32:1)
    at componentFor (/var/folders/gl/c42_2hp924lfn758_fsfbzl80000gn/T/broccoli-329491Acw9O3IGCE1/out-546-packager_runner_embroider_webpack/assets/@ember/-internals/glimmer/index.js:4397:1)
    at lookupComponentPair (/var/folders/gl/c42_2hp924lfn758_fsfbzl80000gn/T/broccoli-329491Acw9O3IGCE1/out-546-packager_runner_embroider_webpack/assets/@ember/-internals/glimmer/index.js:4404:1)
    at ResolverImpl.lookupComponent (/var/folders/gl/c42_2hp924lfn758_fsfbzl80000gn/T/broccoli-329491Acw9O3IGCE1/out-546-packager_runner_embroider_webpack/assets/@ember/-internals/glimmer/index.js:4525:1)
    at resolveComponent (/var/folders/gl/c42_2hp924lfn758_fsfbzl80000gn/T/broccoli-329491Acw9O3IGCE1/out-546-packager_runner_embroider_webpack/assets/@glimmer/opcode-compiler.js:194:1)
    at encodeOp (/var/folders/gl/c42_2hp924lfn758_fsfbzl80000gn/T/broccoli-329491Acw9O3IGCE1/out-546-packager_runner_embroider_webpack/assets/@glimmer/opcode-compiler.js:2126:1)
    at pushOp (/var/folders/gl/c42_2hp924lfn758_fsfbzl80000gn/T/broccoli-329491Acw9O3IGCE1/out-546-packager_runner_embroider_webpack/assets/@glimmer/opcode-compiler.js:2067:1)
    at /var/folders/gl/c42_2hp924lfn758_fsfbzl80000gn/T/broccoli-329491Acw9O3IGCE1/out-546-packager_runner_embroider_webpack/assets/@glimmer/opcode-compiler.js:1715:1
    at Compilers.compile (/var/folders/gl/c42_2hp924lfn758_fsfbzl80000gn/T/broccoli-329491Acw9O3IGCE1/out-546-packager_runner_embroider_webpack/assets/@glimmer/opcode-compiler.js:417:1)
    at compileStatements (/var/folders/gl/c42_2hp924lfn758_fsfbzl80000gn/T/broccoli-329491Acw9O3IGCE1/out-546-packager_runner_embroider_webpack/assets/@glimmer/opcode-compiler.js:2070:1)
    at maybeCompile (/var/folders/gl/c42_2hp924lfn758_fsfbzl80000gn/T/broccoli-329491Acw9O3IGCE1/out-546-packager_runner_embroider_webpack/assets/@glimmer/opcode-compiler.js:2049:1)
    at CompilableTemplateImpl.compile (/var/folders/gl/c42_2hp924lfn758_fsfbzl80000gn/T/broccoli-329491Acw9O3IGCE1/out-546-packager_runner_embroider_webpack/assets/@glimmer/opcode-compiler.js:2032:1)
    at Object.evaluate (/var/folders/gl/c42_2hp924lfn758_fsfbzl80000gn/T/broccoli-329491Acw9O3IGCE1/out-546-packager_runner_embroider_webpack/assets/@glimmer/runtime.js:2973:1)
    at AppendOpcodes.evaluate (/var/folders/gl/c42_2hp924lfn758_fsfbzl80000gn/T/broccoli-329491Acw9O3IGCE1/out-546-packager_runner_embroider_webpack/assets/@glimmer/runtime.js:1052:1)
    at LowLevelVM.evaluateSyscall (/var/folders/gl/c42_2hp924lfn758_fsfbzl80000gn/T/broccoli-329491Acw9O3IGCE1/out-546-packager_runner_embroider_webpack/assets/@glimmer/runtime.js:4214:1)
    at LowLevelVM.evaluateInner (/var/folders/gl/c42_2hp924lfn758_fsfbzl80000gn/T/broccoli-329491Acw9O3IGCE1/out-546-packager_runner_embroider_webpack/assets/@glimmer/runtime.js:4185:1)
    at LowLevelVM.evaluateOuter (/var/folders/gl/c42_2hp924lfn758_fsfbzl80000gn/T/broccoli-329491Acw9O3IGCE1/out-546-packager_runner_embroider_webpack/assets/@glimmer/runtime.js:4178:1)
    at VM.next (/var/folders/gl/c42_2hp924lfn758_fsfbzl80000gn/T/broccoli-329491Acw9O3IGCE1/out-546-packager_runner_embroider_webpack/assets/@glimmer/runtime.js:5009:1)
    at VM._execute (/var/folders/gl/c42_2hp924lfn758_fsfbzl80000gn/T/broccoli-329491Acw9O3IGCE1/out-546-packager_runner_embroider_webpack/assets/@glimmer/runtime.js:4996:1)
    at VM.execute (/var/folders/gl/c42_2hp924lfn758_fsfbzl80000gn/T/broccoli-329491Acw9O3IGCE1/out-546-packager_runner_embroider_webpack/assets/@glimmer/runtime.js:4971:1)
    at /var/folders/gl/c42_2hp924lfn758_fsfbzl80000gn/T/broccoli-329491Acw9O3IGCE1/out-546-packager_runner_embroider_webpack/assets/@glimmer/runtime.js:5054:1
    at runInTrackingTransaction (/var/folders/gl/c42_2hp924lfn758_fsfbzl80000gn/T/broccoli-329491Acw9O3IGCE1/out-546-packager_runner_embroider_webpack/assets/@glimmer/validator.js:138:1)
    at TemplateIteratorImpl.sync (/var/folders/gl/c42_2hp924lfn758_fsfbzl80000gn/T/broccoli-329491Acw9O3IGCE1/out-546-packager_runner_embroider_webpack/assets/@glimmer/runtime.js:5054:1)
    at /var/folders/gl/c42_2hp924lfn758_fsfbzl80000gn/T/broccoli-329491Acw9O3IGCE1/out-546-packager_runner_embroider_webpack/assets/@ember/-internals/glimmer/index.js:4726:1
    at RootState.render (/var/folders/gl/c42_2hp924lfn758_fsfbzl80000gn/T/broccoli-329491Acw9O3IGCE1/out-546-packager_runner_embroider_webpack/assets/@ember/-internals/glimmer/index.js:4695:1)
    at /var/folders/gl/c42_2hp924lfn758_fsfbzl80000gn/T/broccoli-329491Acw9O3IGCE1/out-546-packager_runner_embroider_webpack/assets/@ember/-internals/glimmer/index.js:4988:1
    at inTransaction (/var/folders/gl/c42_2hp924lfn758_fsfbzl80000gn/T/broccoli-329491Acw9O3IGCE1/out-546-packager_runner_embroider_webpack/assets/@glimmer/runtime.js:4090:1)
    at Renderer._renderRoots (/var/folders/gl/c42_2hp924lfn758_fsfbzl80000gn/T/broccoli-329491Acw9O3IGCE1/out-546-packager_runner_embroider_webpack/assets/@ember/-internals/glimmer/index.js:4970:1)
    at Renderer._renderRootsTransaction (/var/folders/gl/c42_2hp924lfn758_fsfbzl80000gn/T/broccoli-329491Acw9O3IGCE1/out-546-packager_runner_embroider_webpack/assets/@ember/-internals/glimmer/index.js:5014:1)
    at Renderer._renderRoot (/var/folders/gl/c42_2hp924lfn758_fsfbzl80000gn/T/broccoli-329491Acw9O3IGCE1/out-546-packager_runner_embroider_webpack/assets/@ember/-internals/glimmer/index.js:4959:1)
    at Renderer._appendDefinition (/var/folders/gl/c42_2hp924lfn758_fsfbzl80000gn/T/broccoli-329491Acw9O3IGCE1/out-546-packager_runner_embroider_webpack/assets/@ember/-internals/glimmer/index.js:4884:1)
    at Renderer.appendOutletView (/var/folders/gl/c42_2hp924lfn758_fsfbzl80000gn/T/broccoli-329491Acw9O3IGCE1/out-546-packager_runner_embroider_webpack/assets/@ember/-internals/glimmer/index.js:4874:1)
    at invokeWithOnError (/var/folders/gl/c42_2hp924lfn758_fsfbzl80000gn/T/broccoli-329491Acw9O3IGCE1/out-546-packager_runner_embroider_webpack/assets/backburner.js:292:1)
    at Queue.flush (/var/folders/gl/c42_2hp924lfn758_fsfbzl80000gn/T/broccoli-329491Acw9O3IGCE1/out-546-packager_runner_embroider_webpack/assets/backburner.js:197:1)
    at DeferredActionQueues.flush (/var/folders/gl/c42_2hp924lfn758_fsfbzl80000gn/T/broccoli-329491Acw9O3IGCE1/out-546-packager_runner_embroider_webpack/assets/backburner.js:360:1)
    at Backburner._end (/var/folders/gl/c42_2hp924lfn758_fsfbzl80000gn/T/broccoli-329491Acw9O3IGCE1/out-546-packager_runner_embroider_webpack/assets/backburner.js:801:1)
    at Backburner._boundAutorunEnd (/var/folders/gl/c42_2hp924lfn758_fsfbzl80000gn/T/broccoli-329491Acw9O3IGCE1/out-546-packager_runner_embroider_webpack/assets/backburner.js:525:1)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)

**Comment by backspace** [comment]
hmm is `test-app` part of a V2 addon? We do have Fastboot present in the project where I used this so it seems supported at least in some contexts.

**Comment by mabab** [comment]
> hmm is `test-app` part of a V2 addon? We do have Fastboot present in the project where I used this so it seems supported at least in some contexts.

Maybe I didn't explain it correctly. I just intentionally added ember fastboot locally to emulate the error I get in the project with fastboot.

**Comment by backspace** [comment]
Thanks for the reproduction repository, when I run it I do see that error as well as this one above it:

```
There was an error running your app in fastboot. More info about the error:
 ReferenceError: document is not defined
    at insertStyleElement (webpack://test-scoped-css/../../.pnpm/style-loader@2.0.0_webpack@5.90.3/node_modules/style-loader/dist/runtime/injectStylesIntoStyleTag.js?:93:15)
```

I’m not sure how to proceed here but I’ll look more into this.

**Comment by gossi** [comment]
I see it working for me with `ember-cli-fastboot` but saw the `ReferenceError: document is not defined` when using it in combination with `prember`.

I couldn't find a proper trace, only the stacktrace to prember build call. But yours above reveals `style-loader` at `v2.0.0` which does use [`document`](https://github.com/webpack-contrib/style-loader/blob/v2.0.0/src/runtime/injectStylesIntoStyleTag.js)

A `pnpm why` reveals, that `ember-auto-import` uses [`style-loader@v2`](https://github.com/embroider-build/ember-auto-import/blob/a1e91449f9686c8229a9bb6ca24111ccfc73eb34/packages/ember-auto-import/package.json#L67).

Oh v4.0.0 is the current version of style-loader at the time of writing, they also do use `document` for their runtime. I think it comes down to that usage.
